#!/usr/bin/env python3
"""Print the Fe UV attenuation include from the EXISTING pinned dielectric.

No new fit: HD2017's l_a=lambda/(4*pi*Im(m)) uses the same explicitly
composite Werner/Henke/size-Drude model as our current electric Fe opacity.
Usage: python3 -B build_fe_uv_attenuation.py --source-directory DIR
       --base-include patch/lagRamses/dust_fe_electric_base_data.inc
The output is deterministic Fortran, suitable for reviewing before inclusion.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path
import numpy as np
from build_fe_grain_optics import FeDielectric, WER_SHA, HENKE_SHA


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--source-directory', type=Path, required=True)
    p.add_argument('--base-include', type=Path, required=True)
    p.add_argument('--atomization', type=Path, default=Path(__file__).resolve().parents[1]/'data/chimes_atomization_atct1130.json')
    a = p.parse_args()
    raw = a.base_include.read_bytes()
    text = raw.decode()
    def array(name):
        body = text.split(':: '+name+'(', 1)[1].split('[', 1)[1].split(']', 1)[0]
        return np.array([float(x.replace('d', 'e')) for x in re.findall(r'[+-]?\d+\.\d+d[+-]\d+', body)])
    ev, radii = array('fe_primary_ev'), array('fe_radius_cm')
    if ev.shape != (9,) or radii.shape != (2,):
        raise ValueError('unexpected base bank layout')
    model = FeDielectric(a.source_directory/'werner_2009_metals.pdf', a.source_directory/'henke_fe.nff')
    lengths = np.stack([1.2398419843320026e-4/ev/(4*np.pi*np.sqrt(model.epsilon(ev,r)).imag)
                        for r in radii], axis=1)
    if not np.isfinite(lengths).all() or np.any(lengths <= 0):
        raise ValueError('nonphysical attenuation length')
    print('! Generated by build_fe_uv_attenuation.py; cm. NOT a new optical fit.')
    print('! Werner SHA256 '+WER_SHA)
    print('! Henke SHA256 '+HENKE_SHA)
    print('! Base include SHA256 '+hashlib.sha256(raw).hexdigest())
    atct_raw = a.atomization.read_bytes()
    if hashlib.sha256(atct_raw).hexdigest() != '0bfa808eda56b7ea41b1a9e083e5379106caa2960f4b8a242f6e2e902606a045':
        raise ValueError('unmatched shared ATcT atomization input')
    atoms = json.loads(atct_raw)['atoms']
    print('! ATcT v1.130 shared CHIMES atomization input SHA256:')
    print('! '+hashlib.sha256(atct_raw).hexdigest())
    print('! H,H+,C,C+ ground-state formation enthalpies, kJ/mol.')
    print('real(real64),parameter :: fe_photon_atct_formation(4)=['+
          ','.join(format(atoms[s],'.3f')+'d0' for s in ('H','H+','C','C+'))+']')
    print('real(real64),parameter :: fe_photon_attenuation_cm(9,2)=reshape([ &')
    values = lengths.ravel(order='F')
    for i in range(0,len(values),3):
        row = ','.join(format(v,'.17e').replace('e','d') for v in values[i:i+3])
        print('  '+row+(', &' if i+3<len(values) else '],[9,2])'))


if __name__ == '__main__':
    main()
